/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import controller.BarangController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class BarangView extends javax.swing.JInternalFrame {
    BarangController bc;
    DefaultTableModel dtm;
    Koneksi konek;
    Statement stmt;
    ResultSet rs;

    /**
     * Creates new form BarangView
     */
    public BarangView() {
        initComponents();
       // textClear();
//        tableBarang();
        bc = new BarangController(this);
        bc.enableForm(false);
        bc.refreshTabel();
    }
    
    public javax.swing.JTextField getKode(){
        return tKode;
    }
    
    public javax.swing.JTextField getNama(){
        return tNama;
    }
    
    public javax.swing.JTextField getJumlah(){
        return tJumlah;
    }
    public javax.swing.JTextField getHarga(){
        return tHarga;
    }
    
    public javax.swing.JComboBox getCmbSatuan(){
        return cmbSatuan;
    }

    public JTable getTabelBarang() {
        return tabelBarang;
    }
    
    
    
    private void textClear(){
        tKode.setText(null);
        tNama.setText(null);
        cmbSatuan.setSelectedIndex(0);
        tJumlah.setText("0");
        tHarga.setText("0");
        tKode.requestFocus();
    }
    
    // isi table
//    void tableBarang() {
//        // tampilan table
//        dtm = new DefaultTableModel();
//        dtm.addColumn("Kode");
//        dtm.addColumn("Nama Barang");
//        dtm.addColumn("Satuan");
//        dtm.addColumn("Jumlah");
//        dtm.addColumn("Harga");
//        jTable1.setModel(dtm);
//        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
//        jTable1.getColumnModel().getColumn(0).setPreferredWidth(100);
//        jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
//        jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
//        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
//        jTable1.getColumnModel().getColumn(4).setPreferredWidth(140);
//        
//        // menampilkan data
//        try {
//            String[] data = new String[5];
//            String sqlSelect = "SELECT * FROM barang ORDER BY kode ASC";
//            konek = new Koneksi();
//            stmt = konek.createStatement();
//            rs = stmt.executeQuery(sqlSelect);
//            while(rs.next()) {
//                data[0] = rs.getString("kode");
//                data[1] = rs.getString("nama");
//                data[2] = rs.getString("satuan");
//                data[3] = rs.getString("jumlah");
//                data[4] = rs.getString("harga");
//                dtm.addRow(data);
//            }
//        } catch(SQLException ex) {
//            Logger.getLogger(BarangView.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
//    
    private void tampilBarang() {
        int row = tabelBarang.getSelectedRow();
        tKode.setText(tabelBarang.getValueAt(row, 0).toString());
        tNama.setText(tabelBarang.getValueAt(row, 1).toString());
        cmbSatuan.setSelectedItem(tabelBarang.getValueAt(row, 2).toString());
        tJumlah.setText(tabelBarang.getValueAt(row, 3).toString());
        tHarga.setText(tabelBarang.getValueAt(row, 4).toString());
        bc.enableForm(true);
        tKode.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        tNama = new javax.swing.JTextField();
        tJumlah = new javax.swing.JTextField();
        tHarga = new javax.swing.JTextField();
        cmbSatuan = new javax.swing.JComboBox<String>();
        bBaru = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelBarang = new javax.swing.JTable();
        bEdit = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setTitle("Form Barang");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Kode");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nama");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Satuan");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Harga");

        tKode.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tNama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tJumlah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        tHarga.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        cmbSatuan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cmbSatuan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Pilih ---", "Kilo", "Liter", "Box" }));

        bBaru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bBaru.setText("Baru");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        bSimpan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        tabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelBarangMouseClicked(evt);
            }
        });
        tabelBarang.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabelBarangComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tabelBarang);

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tNama)
                                .addComponent(tKode)
                                .addComponent(cmbSatuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tHarga)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bBaru)
                            .addGap(18, 18, 18)
                            .addComponent(bSimpan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bHapus))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(tJumlah)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaru)
                    .addComponent(bSimpan)
                    .addComponent(bHapus)
                    .addComponent(bEdit))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        bc.enableForm(true);
        bc.clearForm();
    }//GEN-LAST:event_bBaruActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
//        String kode = tKode.getText();
//        String nama = tNama.getText();
//        String satuan = cmbSatuan.getSelectedItem().toString();
//        int jumlah = Integer.parseInt(tJumlah.getText());
//        int harga = Integer.parseInt(tHarga.getText());
//        Koneksi konek = new Koneksi();
//        Statement stmt = null;
//        
//        try{
//            stmt = konek.createStatement();
//            String sqlInsert = "INSERT INTO barang "
//                   + "(kode,nama,satuan,jumlah,harga) "
//                   + "VALUES ('"+kode+"','"+nama+"','"+satuan+"','"
//                   + jumlah+"','"+harga+"')";
//            stmt.executeUpdate(sqlInsert);
//            JOptionPane.showMessageDialog(this, "Data berhasil di simpan!",
//                        "Informasi",JOptionPane.INFORMATION_MESSAGE);
//        }catch(SQLException ex){
//            try{
//                if(ex.getErrorCode() == 1062){
//                    int confr = JOptionPane.showConfirmDialog(null, 
//                        "Kode Barang sudah ada! \nApakah ingin mengubah data?",
//                        "Peringatan", JOptionPane.YES_NO_OPTION);
//                    if(confr == 0){
//                        String sqlUpdate = "UPDATE barang SET kode='"+kode
//                               +"',nama='"+nama+"',satuan='"+satuan
//                               +"',jumlah='"+jumlah+"',harga='"+harga
//                               +"' WHERE kode='"+kode+"'";
//                        stmt.executeUpdate(sqlUpdate);
//                    }else{
//                        textClear();
//                    }
//                }
//            }catch(SQLException ex1){
//                
//            }
//        }
//        textClear();
    
    bc.simpan();
    bc.clearForm();
    bc.enableForm(false);
    bc.refreshTabel();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
//        try{
//            String kode = tKode.getText();
//            Koneksi konek = new Koneksi();
//            Statement stmt = konek.createStatement();
//            int confr = JOptionPane.showConfirmDialog(null, 
//                "apakah data dengan kode "+kode+" akan dihapus?","Konfirmasi",
//                JOptionPane.YES_NO_OPTION);
//            if(confr == 0){
//                String sqlDelete = "DELETE FROM barang WHERE kode='"+kode+"'";
//                stmt.executeUpdate(sqlDelete);
//                textClear();
//            }
//        }catch(SQLException ex){
//            System.out.println("Error : "+ex.getMessage());
//        }
//        tableBarang();
        bc.delete();
        bc.refreshTabel();
    }//GEN-LAST:event_bHapusActionPerformed

    private void tabelBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelBarangMouseClicked
       tampilBarang();
    }//GEN-LAST:event_tabelBarangMouseClicked

    private void tabelBarangComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabelBarangComponentShown
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tabelBarangComponentShown

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        bc.update();
        bc.refreshTabel();
    }//GEN-LAST:event_bEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JComboBox<String> cmbSatuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tHarga;
    private javax.swing.JTextField tJumlah;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tNama;
    private javax.swing.JTable tabelBarang;
    // End of variables declaration//GEN-END:variables
}
