/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JMenu;
import javax.swing.JOptionPane;
import view.BarangView;
import view.PenjualanView;

/**
 *
 * @author Admin
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    public JMenu getLabelPengguna() {
        return LabelPengguna;
    }

    public JMenu getjMenu2() {
        return jMenu2;
    }

    public JMenu getMenuLogout() {
        return menuLogout;
    }

    public JMenu getjMenu1() {
        return jMenu1;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemBarang = new javax.swing.JMenuItem();
        itemPelanggan = new javax.swing.JMenuItem();
        itemUser = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemPenjualan = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        laporanBarang = new javax.swing.JMenuItem();
        laporanPelanggan = new javax.swing.JMenuItem();
        laporanPenjualan = new javax.swing.JMenuItem();
        laporanUser = new javax.swing.JMenuItem();
        LabelPengguna = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 501, Short.MAX_VALUE)
        );

        jMenu1.setText("Master");

        itemBarang.setText("Barang");
        itemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBarangActionPerformed(evt);
            }
        });
        jMenu1.add(itemBarang);

        itemPelanggan.setText("Pelanggan");
        itemPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPelangganActionPerformed(evt);
            }
        });
        jMenu1.add(itemPelanggan);

        itemUser.setText("User");
        itemUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUserActionPerformed(evt);
            }
        });
        jMenu1.add(itemUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        itemPenjualan.setText("Penjualan");
        itemPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPenjualanActionPerformed(evt);
            }
        });
        jMenu2.add(itemPenjualan);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        laporanBarang.setText("Barang");
        laporanBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBarangActionPerformed(evt);
            }
        });
        jMenu3.add(laporanBarang);

        laporanPelanggan.setText("Pelanggan");
        laporanPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPelangganActionPerformed(evt);
            }
        });
        jMenu3.add(laporanPelanggan);

        laporanPenjualan.setText("Penjualan");
        laporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPenjualanActionPerformed(evt);
            }
        });
        jMenu3.add(laporanPenjualan);

        laporanUser.setText("User");
        laporanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanUserActionPerformed(evt);
            }
        });
        jMenu3.add(laporanUser);

        jMenuBar1.add(jMenu3);

        LabelPengguna.setText("Pengguna");
        LabelPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabelPenggunaActionPerformed(evt);
            }
        });
        jMenuBar1.add(LabelPengguna);

        menuLogout.setText("Logout");
        menuLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuLogoutMouseClicked(evt);
            }
        });
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBarangActionPerformed
        // TODO add your handling code here:
        BarangView barang = new BarangView();
        barang.setVisible(true);
        desktop.add(barang);
        try{
            barang.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_itemBarangActionPerformed

    private void itemPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPenjualanActionPerformed
        // TODO add your handling code here:
        PenjualanView jual = new PenjualanView();
        jual.setVisible(true);
        desktop.add(jual);
        try {
            jual.setSelected(true);
        }catch (Exception e) {}
    }//GEN-LAST:event_itemPenjualanActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void LabelPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabelPenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabelPenggunaActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuLogoutMouseClicked
        // TODO add your handling code here:
        int k = JOptionPane.showConfirmDialog(this,"Apakah Anda Yakin ?","Konfirmasi",
                JOptionPane.YES_NO_OPTION);
        if (k ==0){
            this.dispose();
            LoginView login = new LoginView();
            login.setVisible(true);
        }
    }//GEN-LAST:event_menuLogoutMouseClicked

    private void itemPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPelangganActionPerformed
        // TODO add your handling code here:
        PelangganView pelanggan = new PelangganView();
        pelanggan.setVisible(true);
        desktop.add(pelanggan);
        try{
            pelanggan.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_itemPelangganActionPerformed

    private void itemUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUserActionPerformed
        // TODO add your handling code here:
        UserView user = new UserView();
        user.setVisible(true);
        desktop.add(user);
        try{
            user.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_itemUserActionPerformed

    private void laporanBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBarangActionPerformed
        // TODO add your handling code here:
        LaporanBarangView laporanbarang = new LaporanBarangView();
        laporanbarang.setVisible(true);
        desktop.add(laporanbarang);
        try{
            laporanbarang.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_laporanBarangActionPerformed

    private void laporanPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPelangganActionPerformed
        // TODO add your handling code here:
        LaporanPelangganView laporanpelanggan = new LaporanPelangganView();
        laporanpelanggan.setVisible(true);
        desktop.add(laporanpelanggan);
        try{
            laporanpelanggan.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_laporanPelangganActionPerformed

    private void laporanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laporanUserActionPerformed

    private void laporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPenjualanActionPerformed
        // TODO add your handling code here:
        LaporanPenjualanView laporanpenjualan = new LaporanPenjualanView();
        laporanpenjualan.setVisible(true);
        desktop.add(laporanpenjualan);
        try{
            laporanpenjualan.setSelected(true);
        }catch(java.beans.PropertyVetoException e){
            
        }
    }//GEN-LAST:event_laporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu LabelPengguna;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuItem itemBarang;
    private javax.swing.JMenuItem itemPelanggan;
    private javax.swing.JMenuItem itemPenjualan;
    private javax.swing.JMenuItem itemUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem laporanBarang;
    private javax.swing.JMenuItem laporanPelanggan;
    private javax.swing.JMenuItem laporanPenjualan;
    private javax.swing.JMenuItem laporanUser;
    private javax.swing.JMenu menuLogout;
    // End of variables declaration//GEN-END:variables
}
