/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import config.Koneksi;
import controller.PelangganController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class PelangganView extends javax.swing.JInternalFrame {

    PelangganController pc;
    DefaultTableModel dtm;
    Koneksi konek;
    Statement stmt;
    ResultSet rs;
    
    public PelangganView() {
        initComponents();
        pc = new PelangganController(this);
        pc.enableForm(false);
        pc.refreshTabel();
    }

    public JButton getbBaru() {
        return bBaru;
    }

    public JButton getbEdit() {
        return bEdit;
    }

    public JButton getbHapus() {
        return bHapus;
    }

    public JButton getbSimpan() {
        return bSimpan;
    }

    public JTextField gettEmail() {
        return tEmail;
    }

    public JTextField gettKode() {
        return tKode;
    }

    public JTextField gettNama() {
        return tNama;
    }

    public JTextArea gettAlamat() {
        return tAlamat;
    }
    

    public JTable getTabelPelanggan() {
        return TabelPelanggan;
    }
    
    
    
    private void textClear(){
        tKode.setText(null);
        tNama.setText(null);
        tEmail.setText(null);
        tAlamat.setText(null);
        tKode.requestFocus();
    }
    
    void tablePelanggan(){
//        dtmodel = new DefaultTableModel();
//        dtmodel.addColumn("Kode");
//        dtmodel.addColumn("Nama");
//        dtmodel.addColumn("Email");
//        dtmodel.addColumn("Alamat");
//        TabelPelanggan.setModel(dtmodel);
//        TabelPelanggan.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
//        TabelPelanggan.getColumnModel().getColumn(0).setPreferredWidth(100);
//        TabelPelanggan.getColumnModel().getColumn(1).setPreferredWidth(150);
//        TabelPelanggan.getColumnModel().getColumn(2).setPreferredWidth(100);
//        TabelPelanggan.getColumnModel().getColumn(3).setPreferredWidth(200);
//        
//        try {
//            String[] data = new String[4];
//            String sqlSelect = "SELECT * FROM pelanggan ORDER BY kode ASC";
//            konek = new Koneksi();
//            stmnt = konek.createStatement();
//            result = stmnt.executeQuery(sqlSelect);
//            while(result.next()) {
//                data[0] = result.getString("kode");
//                data[1] = result.getString("nama");
//                data[2] = result.getString("email");
//                data[3] = result.getString("alamat");
//                dtmodel.addRow(data);
//            }
//        } catch(SQLException ex) {
//            Logger.getLogger(BarangView.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }
    
    private void tampilPelanggan() {
        int row = TabelPelanggan.getSelectedRow();
        tKode.setText(TabelPelanggan.getValueAt(row, 0).toString());
        tNama.setText(TabelPelanggan.getValueAt(row, 1).toString());
        tEmail.setText(TabelPelanggan.getValueAt(row, 2).toString());
        tAlamat.setText(TabelPelanggan.getValueAt(row, 3).toString());
        pc.enableForm(true);
        tKode.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lKode = new javax.swing.JLabel();
        tKode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tNama = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        bBaru = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelPelanggan = new javax.swing.JTable();
        bEdit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pelanggan View");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lKode.setText("Kode");

        jLabel7.setText("Nama");

        jLabel8.setText("Email");

        jLabel9.setText("Alamat");

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane1.setViewportView(tAlamat);

        bBaru.setText("Baru");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        TabelPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode", "Nama", "Email", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelPelanggan);
        if (TabelPelanggan.getColumnModel().getColumnCount() > 0) {
            TabelPelanggan.getColumnModel().getColumn(0).setResizable(false);
            TabelPelanggan.getColumnModel().getColumn(1).setResizable(false);
            TabelPelanggan.getColumnModel().getColumn(2).setResizable(false);
        }

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lKode)
                            .addGap(42, 42, 42)
                            .addComponent(tKode))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bBaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bHapus))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(39, 39, 39)
                                .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lKode)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel8)
                        .addGap(3, 3, 3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHapus)
                    .addComponent(bEdit)
                    .addComponent(bSimpan)
                    .addComponent(bBaru))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        pc.enableForm(true);
        pc.clearForm();
    }//GEN-LAST:event_bBaruActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
//        String kode = tKode.getText();
//        String nama = tNama.getText();
//        String email = tEmail.getText();
//        String alamat = tAlamat.getText();
//        
//        Koneksi koneksi = new Koneksi();
//        Statement stmt = null;
//        
//        try {
//            stmt = koneksi.createStatement();
//            String sqlInsert = "INSERT INTO pelanggan"
//                    + "(kode,nama,email,alamat)"
//                    + "VALUES ('"+ kode +"','"+nama+"','"+email+"','"+alamat+"')";
//            stmt.executeUpdate(sqlInsert);
//            JOptionPane.showMessageDialog(this, "Data berhasil di simpan!",
//                        "Informasi",JOptionPane.INFORMATION_MESSAGE);
//        } catch (SQLException ex) {
//            try {
//                if(ex.getErrorCode() == 1062){
//                    int confr = JOptionPane.showConfirmDialog(null, 
//                        "Kode Barang sudah ada! \nApakah ingin mengubah data?",
//                        "Peringatan", JOptionPane.YES_NO_OPTION);
//                    if(confr == 0){
//                        String sqlUpdate = "UPDATE barang SET kode='"+kode
//                               +"',nama='"+nama+"','"+email+"','"+alamat+"'"
//                               +"' WHERE kode='"+kode+"'";
//                        stmt.executeUpdate(sqlUpdate);
//                    }else{
//                        textClear();
//                    }
//                }
//            } catch (SQLException ex1) {}
//        }
//        textClear();
    pc.simpanp();
    pc.clearForm();
    pc.enableForm(false);
    pc.refreshTabel();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
//        try{
//            String kode = tKode.getText();
//            Koneksi konek = new Koneksi();
//            Statement stmt = konek.createStatement();
//            int confr = JOptionPane.showConfirmDialog(null, 
//                "apakah data dengan kode "+kode+" akan dihapus?","Konfirmasi",
//                JOptionPane.YES_NO_OPTION);
//            if(confr == 0){
//                String sqlDelete = "DELETE FROM pelanggan WHERE kode='"+kode+"'";
//                stmt.executeUpdate(sqlDelete);
//                textClear();
//            }
//        }catch(SQLException ex){
//            System.out.println("Error : "+ex.getMessage());
//        }
//        tablePelanggan();
        pc.deletep();
        pc.refreshTabel();
    }//GEN-LAST:event_bHapusActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_formMouseClicked

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
//        pc.update();
//        pc.refreshTabel();
        pc.updatep();
        pc.refreshTabel();
    }//GEN-LAST:event_bEditActionPerformed

    private void TabelPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPelangganMouseClicked
        // TODO add your handling code here:
        tampilPelanggan();
    }//GEN-LAST:event_TabelPelangganMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelPelanggan;
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lKode;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tKode;
    private javax.swing.JTextField tNama;
    // End of variables declaration//GEN-END:variables
}
