package view;

import controller.UserController;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class UserView extends javax.swing.JInternalFrame {
    UserController uc;
    ButtonGroup GroupHakakses;
    private String hakakses;
    private String vpassword,vmd5,vsha1;

    public UserView() {
        initComponents();
        uc = new UserController(this);
        uc.enableForm(false);
        //bSimpan.setEnabled(false);
        uc.refreshTabel();
        
        jRadio_L.setActionCommand("kasir");
        jRadio_P.setActionCommand("pemilik");
 
        GroupHakakses = new ButtonGroup();
        GroupHakakses.add(jRadio_L);
        GroupHakakses.add(jRadio_P);
        
    }
    
    
    public String getHakakses(){
        return hakakses = GroupHakakses.getSelection().getActionCommand();
    }
    public void clearHakakses(){
        GroupHakakses.clearSelection();
    }
    
    public JTextArea gettAlamat() {
        return tAlamat;
    }

    public JTextField gettNamaLengkap() {
        return tNamaLengkap;
    }

    public JTextField gettPassword() {
        
        return tPassword;
    }

    public JTextField gettUsername() {
        return tUsername;
    }

    public JTable getTabelUser() {
        return TabelUser;
    }

    public JButton getbSimpan() {
        return bSimpan;
    }
    
    
    
    private void tampilUser() {
       
        int row = TabelUser.getSelectedRow();
         
        tUsername.setText(TabelUser.getValueAt(row, 0).toString());
        tPassword.setText(TabelUser.getValueAt(row, 1).toString());
        if (!TabelUser.getValueAt(row, 2).toString().equals("pemilik")) { 
            jRadio_L.setSelected(true);
        } else {
            jRadio_P.setSelected(true);
        }
        tNamaLengkap.setText(TabelUser.getValueAt(row, 3).toString());
        tAlamat.setText(TabelUser.getValueAt(row, 4).toString());
        uc.enableForm(true);
        tUsername.setEnabled(false);
    }
    
    
    
     private String toSHA1(){
            vpassword=tPassword.getText();
            String encPass=null;
         try{
            MessageDigest digest=MessageDigest.getInstance("Sha1");
            digest.update(vpassword.getBytes(),0,vpassword.length());
            encPass=new BigInteger(1,digest.digest()).toString(16);
            vsha1=encPass.toUpperCase();
            tPassword.setText(vsha1);
         }
         catch(Exception e){
            e.printStackTrace();
         }
            return encPass;
         }
    
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bJenisKelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lNama = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tUsername = new javax.swing.JTextField();
        jRadio_L = new javax.swing.JRadioButton();
        jRadio_P = new javax.swing.JRadioButton();
        bEdit = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        tNamaLengkap = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelUser = new javax.swing.JTable();
        tPassword = new javax.swing.JPasswordField();
        bBaru = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("FORM DATA DIRI");

        lNama.setText("Username");

        jLabel2.setText("Hak Akses");

        jLabel3.setText("Password");

        jLabel5.setText("Nama Lengkap");

        jLabel7.setText("Alamat");

        tUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUsernameActionPerformed(evt);
            }
        });

        bJenisKelamin.add(jRadio_L);
        jRadio_L.setText("Kasir");

        bJenisKelamin.add(jRadio_P);
        jRadio_P.setText("Pemilik");
        jRadio_P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_PActionPerformed(evt);
            }
        });

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        tNamaLengkap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNamaLengkapActionPerformed(evt);
            }
        });

        tAlamat.setColumns(20);
        tAlamat.setRows(5);
        jScrollPane1.setViewportView(tAlamat);

        TabelUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelUser);

        bBaru.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        bBaru.setText("Baru");
        bBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBaruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lNama)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jRadio_L)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jRadio_P)
                                .addGap(21, 21, 21))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(tNamaLengkap)
                            .addComponent(tUsername)
                            .addComponent(tPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(bBaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bHapus)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lNama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_L)
                    .addComponent(jRadio_P)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tNamaLengkap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBaru)
                    .addComponent(bSimpan)
                    .addComponent(bEdit)
                    .addComponent(bHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUsernameActionPerformed

    private void tNamaLengkapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNamaLengkapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNamaLengkapActionPerformed

    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        
        toSHA1();
        uc.simpanu();
        uc.refreshTabel();
        uc.clearForm();
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        int confr = JOptionPane.showConfirmDialog(null,
            "Yakin Mengubah Data ?",
            "Peringatan", JOptionPane.YES_NO_OPTION);
        if(confr == 0){
            uc.updateu();
            uc.clearForm();
            uc.refreshTabel();
        }else{

        };
    }//GEN-LAST:event_bEditActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        int confr = JOptionPane.showConfirmDialog(null,
            "Yakin Menghapus Data ?",
            "Peringatan", JOptionPane.YES_NO_OPTION);
        if(confr == 0){
            uc.deleteu();
            uc.clearForm();
            uc.refreshTabel();
        }else{

        };
    }//GEN-LAST:event_bHapusActionPerformed

    private void jRadio_PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_PActionPerformed

    private void bBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBaruActionPerformed
        // TODO add your handling code here:
        uc.enableForm(true);
        uc.clearForm();
    }//GEN-LAST:event_bBaruActionPerformed

    private void TabelUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelUserMouseClicked
        // TODO add your handling code here:
         tampilUser();
         bSimpan.setEnabled(false);
    }//GEN-LAST:event_TabelUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelUser;
    private javax.swing.JButton bBaru;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.ButtonGroup bJenisKelamin;
    private javax.swing.JButton bSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio_L;
    private javax.swing.JRadioButton jRadio_P;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lNama;
    private javax.swing.JTextArea tAlamat;
    private javax.swing.JTextField tNamaLengkap;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUsername;
    // End of variables declaration//GEN-END:variables

}
